### PR TITLE
Add Russian locale

### PR DESCRIPTION
**Pull request by korun**
Hi! This request just add russian locale to the app, btw, thanks for it!

### CODE REVIEW

**Comment by korun** [comment]
The server-side translation will be a little later.

**Comment by lentschi** [comment]
Ah, awesome! Thank you so much! :smile: 
I'm not sure when I have time to build a new release for the Play Store (I have some bugs in the current master that I want to fix first.), but I hope soon!

**Comment by lentschi** [comment]
@korun I'm ready to deploy version 1.9 this weekend. There's one more translation that I added to the client using Google translate:

```json
{"Use system language for date format (instead of language chosen above)": "Используйте системный язык для формата даты (вместо языка, выбранного выше)"}
```

Is that fine?

Also there is the Google Play Store entry:

```
- Scan a product's barcode before you put it in your fridge, cupboard etc.
- Manually add details, like the expiration date or a product image
- Sort by expiration date, time of adding an entry, or name.
- Be reminded before a product expires (automatic alert at a configurable time of the day)
- Synchronize the entries with other users and devices.
- Share locations with other users.
- Customizable recipe search
- Offline mode (in case you're only using one device)


For developers: 
===

This project is open source - you can clone it from GitHub: 
https://github.com/lentschi/expiry_sync

Implementing the API docs, that can be found at GitHub, you can add your own servers here:
https://nameless-oasis-2639.herokuapp.com
```

Google translates that to:
```
- Сканируйте штрих-код продукта, прежде чем положить его в холодильник, шкаф и т. Д.
- Вручную добавить детали, такие как срок годности или изображение продукта
- Сортировка по дате истечения срока, времени добавления записи или имени.
- Напоминание до истечения срока действия продукта (автоматическое оповещение в настраиваемое время суток)
- Синхронизировать записи с другими пользователями и устройствами.
- Поделитесь местоположениями с другими пользователями.
- Настраиваемый поиск рецептов
- Автономный режим (если вы используете только одно устройство)


Для разработчиков:
===

Этот проект с открытым исходным кодом - вы можете клонировать его из GitHub:
https://github.com/lentschi/expiry_sync

Реализуя API-документы, которые можно найти на GitHub, вы можете добавить свои собственные серверы здесь:
https://nameless-oasis-2639.herokuapp.com
```

Can I publish it with this? (Don't put too much work into that - I suspect noone really reads all that anyway ;-) )

**Comment by lentschi** [comment]
@korun Ah, and also: Would you like to be mentioned as a translator (with a link or something) on the app's *'About'* page?

**Comment by korun** [comment]
> `{"Use system language for date format (instead of language chosen above)": "Используйте системный язык для формата даты (вместо языка, выбранного выше)"}`

Yes, this is good!

And it will more correct for Play Store to use this:
```
- Сканируйте штрих-код продукта, прежде чем положить его в холодильник, шкаф и т.д.
- Добавляйте подробности, например срок годности или изображение продукта.
- Сортируйте по дате истечения срока, времени добавления записи или названию.
- Получайте уведомление до истечения срока годности продукта (автоматическое оповещение в настраиваемое время суток).
- Синхронизируйте записи с другими пользователями и устройствами.
- Делитесь местами хранения с другими пользователями.
- Настраиваемый поиск рецептов.
- Автономный режим (если вы используете только одно устройство).

Для разработчиков:
===

Это проект с открытым исходным кодом - вы можете клонировать его из GitHub:
https://github.com/lentschi/expiry_sync

Следуя API-документам, которые можно найти на GitHub, вы можете добавлять свои собственные сервера здесь:
https://nameless-oasis-2639.herokuapp.com
```

---

About translator-mentioning, yes, thank you, you can mention just my name and link to a GitHub profile, but with my reviewer: Liza Khruslova (she doesn't have a GitHub profile btw, so her name will be enough).

**Comment by korun** [comment]
And about server translations: I keep it in mind, but I don't have enough free time at the moment :sweat_smile:

**Comment by lentschi** [comment]
@korun Thanks so much again!

So, is it fine, if I add the following to the about page:

> Большое спасибо за переводы на русский язык:
> 
> -  Иван - https://github.com/korun
> - Лиза Кхруслова

Is Korun your last name? -> Should I change it to Иван Корун?

**Comment by korun** [comment]
My last name is Korunkov, like in commit-message. :)
If you want to write it in russian, prefer to do it like:
```
Большое спасибо за переводы на русский язык:

Ивану Корункову - https://github.com/korun
Лизе Хрусловой
```
Thanks

**Comment by lentschi** [comment]
@korun I just published version 1.9, which includes your translations.
Thanks a lot!

**Pull request merged**
